version: '3.6'

services:
  app:
      container_name: app
      build:
        context: ./app
        dockerfile: Dockerfile
      ports:
        - '3000:3000'  # ホストとコンテナ内のReactの起動ポートを接続
      volumes:
        - ./app:/usr/src/app:cached  # ホストのappディレクトリをマウント
        - /usr/src/app/node_modules  # 上書きされないようにボリュームを作成
      tty: true
